### create User
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Índio Medeiros",
    "email": "bboyindio@gmail.com",
    "nickname": "Ìndio",
    "password": "12345678"  
}

### login
POST http://localhost:3003/user/login 
Content-Type: application/json

{
   "email": "bboyindio@gmail.com",
   "password": "12345678"    
}

### create Image
POST http://localhost:3003/image/create
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTY2M2FlLWQ5YjUtNGI3ZS04NTQxLWRlNjI5MTViNjMwNSIsImlhdCI6MTYxNDE4ODQwNiwiZXhwIjoxNjE0Mjc0ODA2fQ.oirNr4rLpCLosMSZLS9v0nN3SxB1J-kgKVq-KsQa39U 

{
	"subtitle": "Crianças brincando no deserto",
	"file": "https://pixabay.com/images/id-5833685/",
	"tags": "Crianças, Infância, Jogos, Jogar, Diversão, Brincalhão",
	"collection": "vida"    
}
###get all images
GET http://localhost:3003/image/all
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTY2M2FlLWQ5YjUtNGI3ZS04NTQxLWRlNjI5MTViNjMwNSIsImlhdCI6MTYxNDE4ODQwNiwiZXhwIjoxNjE0Mjc0ODA2fQ.oirNr4rLpCLosMSZLS9v0nN3SxB1J-kgKVq-KsQa39U

###get images by id
GET http://localhost:3003/image/58f9a328-70d5-4506-96ee-1b420c81d94f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTY2M2FlLWQ5YjUtNGI3ZS04NTQxLWRlNjI5MTViNjMwNSIsImlhdCI6MTYxNDE4ODQwNiwiZXhwIjoxNjE0Mjc0ODA2fQ.oirNr4rLpCLosMSZLS9v0nN3SxB1J-kgKVq-KsQa39U

###search images
GET http://localhost:3003/image/search?dataSearch=Crianças
Content-Type: application/json
